# Generated by Django 3.1.7 on 2021-04-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='order',
            name='order_day',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_long',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='wishes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
