# Generated by Django 3.1.7 on 2021-04-07 12:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210402_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_kurz', models.CharField(default='', max_length=256)),
                ('content_lang', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
