# Generated by Django 3.1.7 on 2021-05-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='session_time',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
